{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Drug Subreddit Analysis (Personal Experience)",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/pilot/Q1",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "tsv", 

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "",

    "data_files": [
       "data_files/drug.csv"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text",
        "context_key": "context"
    },


    "user_config": {

      "allow_all_users": True,
      
      "users": [  ],
    },

    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,

    "surveyflow": {
      "on": True,
      #"order" : ['pre_annotation', 'prestudy_passed', 'prestudy_failed', 'post_annotation'],
      "order" : ['pre_annotation', 'post_annotation'],
      "pre_annotation": ['surveyflow/intro.jsonl', 'surveyflow/instruction.jsonl', 'surveyflow/consent.jsonl'],
      "post_annotation": ['surveyflow/experience.jsonl', 'surveyflow/demographic_questions.jsonl','surveyflow/end.jsonl'],
      # If set, we will automatically generate testing questions similar to the annotation instances, but explicitly ask the annotator to choose one option
      "testing": ['surveyflow/testing.jsonl'],
    },
    
     "prestudy": {
        "on": False,
        "minimum_score": 0.8,
        "groundtruth_key": 'whether_match',
        "question_key": 'Whether the presented sentences are discussing the same scientific finding',
        "answer_mapping": {'Yes': True, 'No': False},
        "pass_page": 'surveyflow/prestudy_pass.jsonl',
        "fail_page": 'surveyflow/prestudy_fail.jsonl'
    },

    "annotation_schemes": [      

        {
            "annotation_type": "radio",
            "name": "Action",
            "description": "What is the primary purpose of the post? Is the post primarily asking for something from the community (Inquisition)? Or is it meant to share stories and lived experiences (Disclosure)?",
            "labels": [
               "Inquisition", "Disclosure"
            ],

            # If true, numbers [1-len(labels)] will be bound to each
            # label. Annotations with more than 10 are not supported with this
            # simple keybinding and will need to use the full item specification
            # to bind all labels to keys.
            "sequential_key_binding": True,                        
        }, 
        {
            "annotation_type": "multiselect",
            "name": "Topics",
            "description": "This is the main theme of the post",
            "labels": [
                { "name": "Symptoms",
                  "tooltip_file": "tooltips/Symptoms.html"
                },
                {
                  "name": "Guidance",
                  "tooltip_file": "tooltips/Guidance.html"
                 },

                { "name": "Withdrawls",
                  "tooltip_file": "tooltips/Withdrawal.html"
                },

                { "name": "Recovery",
                  "tooltip_file": "tooltips/Recovery.html",
                },
                { "name": "Relapse",
                  "tooltip_file": "tooltips/Relapse.html",
                },
                { "name": "Sobriety",
                  "tooltip_file": "tooltips/Sobriety.html",
                },
                { "name": "Overdose",
                  "tooltip_file": "tooltips/Overdose.html",
                },
                { "name": "Social Support",
                  "tooltip_file": "tooltips/Social_Support.html",
                },
                { "name": "Cultural Reference",
                  "tooltip_file": "tooltips/Culture_Reference.html"
                },
                { "name": "Values",
                  "tooltip_file": "tooltips/Values.html"
                },
                { "name": "Banter",
                  "tooltip_file": "tooltips/Banter.html"
                },
                { "name": "Not Applicable",
                  "tooltip_file": "tooltips/NA.html"
                },
                
            ]
        },
        

    ],

    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces
    # you may use templates in our lib, if you want to use your own template,
    # please replace the string as a path to the template
    "html_layout": "default",

    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include:
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    # if you want to use your own template,
    # please replace the string as a path to the template
    "base_html_template": "default",
    "header_file": "default",

    # This is where the actual HTML files will be generated
    "site_dir": "default"

}
